//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDK0402App.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Int { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> PenId { get; set; }
        public string Count { get; set; }
        public Nullable<int> ClientId { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Pen Pen { get; set; }
    }
}
